version: '3.7'
services:
  # Banco de dados
  db_promobit_teste:
    image: mysql:5.7
    container_name: db_promobit_teste
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
      # tem um problema aqui, o mysql não cria os arquivos como se meu usuario fosse o owner
      # por isso quando eu dou restart pelo vs code dá um problema de acesso negado que é resolvido, ou quando eu rodo
      # chown -R 755 docker-compose/mysql pra permitir meu usuario de mexer na pasta, ou quando removo a pasta
    networks:
      - application

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db_promobit_teste
    depends_on:
      - db_promobit_teste
    ports:
      - "8080:80"
    links:
      - db_promobit_teste
    networks:
      - application

  app:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: app
    depends_on:
      - db_promobit_teste
    restart: unless-stopped
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=mcc.localhost
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - application

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - application
networks:
  application:
    name: "teste-cadastro"
